Villager state machine framework + implementation of a few states
openblack/openblack pull request #285
Opened 2021-03-08 13:48 UTC by bwrsandman

Depends on:
- [ ]  #265 Map look-up
- [ ] #259 Villagers being assigned abodes
- [ ] #275 (Sorta)  Villager pathfinding
- [ ] #276 (Optionally) Better logging with categories

2021-03-23 02:13 UTC, raffclar commented
I know this is WIP so no rush but I'm getting this

```
D:\openblack\src\Entities/Components/Villager.h(240): warning C4458: declaration of 'tribe' hides class member
D:\openblack\src\Entities/Components/Villager.h(284): note: see declaration of 'openblack::entities::components::Villager::tribe'
D:\openblack\src\Entities/Components/Villager.h(242): warning C4458: declaration of 'lifeStage' hides class member
D:\openblack\src\Entities/Components/Villager.h(282): note: see declaration of 'openblack::entities::components::Villager::lifeStage'
D:\openblack\src\Entities/Components/Villager.h(243): warning C4458: declaration of 'role' hides class member
D:\openblack\src\Entities/Components/Villager.h(285): note: see declaration of 'openblack::entities::components::Villager::role'
D:\openblack\src\Entities/Components/Villager.h(244): error C2064: term does not evaluate to a function taking 1 arguments
D:\openblack\src\Entities/Components/Villager.h(245): error C2064: term does not evaluate to a function taking 1 arguments
D:\openblack\src\Entities/Components/Villager.h(246): error C2064: term does not evaluate to a function taking 1 arguments
D:\openblack\src\Entities/Components/Villager.h(254): error C3536: 'h1': cannot be used before it is initialized
D:\openblack\src\Entities/Components/Villager.h(254): error C3536: 'h2': cannot be used before it is initialized
D:\openblack\src\Entities/Components/Villager.h(254): error C3536: 'h3': cannot be used before it is initialized
```

2022-01-09 19:48 UTC, bwrsandman commented on src/Entities/Components/Fixed.cpp
> + * Copyright (c) 2018-2021 openblack developers
2022

2022-01-09 19:48 UTC, bwrsandman commented on src/Entities/Components/Fixed.h
> + * Copyright (c) 2018-2021 openblack developers
2022

2022-01-09 19:48 UTC, bwrsandman commented on src/Entities/Components/Footpath.cpp
> + * Copyright (c) 2018-2021 openblack developers
2022

2022-01-09 19:48 UTC, bwrsandman commented on src/Entities/Components/Mobile.cpp
> + * Copyright (c) 2018-2021 openblack developers
2022

2022-01-09 19:49 UTC, bwrsandman commented on src/Entities/Components/Town.cpp
> + * Copyright (c) 2018-2021 openblack developers
2022

2022-01-09 19:49 UTC, bwrsandman commented on src/Entities/Components/Transform.cpp
> + * Copyright (c) 2018-2021 openblack developers
2022

2022-01-09 19:49 UTC, bwrsandman commented on src/Entities/Map.cpp
> + * Copyright (c) 2018-2021 openblack developers
2022

2022-01-09 19:49 UTC, bwrsandman commented on src/Entities/Map.h
> + * Copyright (c) 2018-2021 openblack developers
2022

2022-01-09 19:49 UTC, bwrsandman commented on src/InfoConstants.cpp
> + * Copyright (c) 2018-2021 openblack developers
2022

2022-01-09 19:49 UTC, bwrsandman commented on src/Entities/Components/Abode.cpp
> + * Copyright (c) 2018-2021 openblack developers
2022

2022-01-09 19:49 UTC, bwrsandman commented on src/Common/Spiral.cpp
> + * Copyright (c) 2018-2021 openblack developers
2022

2022-02-21 04:15 UTC, bwrsandman commented
I dropped changes in the WIP commit but here it is for reference: https://github.com/openblack/openblack/pull/285/commits/cf319523

2022-02-21 04:16 UTC, bwrsandman commented
Also noticed through this PR, a lot of logging is done without the macro

2022-02-21 12:17 UTC, bwrsandman commented on src/ECS/Components/Field.h
> +	static constexpr float radius2D = 5.0f;
Can we get this from info constants?

2022-02-21 12:43 UTC, bwrsandman commented on src/ECS/Systems/LivingActionSystem.cpp
> +	SPDLOG_LOGGER_ERROR(spdlog::get("game"), "Villager #{}: Stuck in an invalid state",
Add a new logger called "ai"

2022-04-21 02:26 UTC, bwrsandman commented on src/ECS/Components/Abode.h
> +	bool IsFunctional() const { return true; }
Move logic to manager

2022-04-21 02:26 UTC, bwrsandman commented on src/ECS/Archetypes/VillagerArchetype.cpp
> +	thread_local std::uniform_int_distribution<uint16_t> duration_distribution(1, 500);
Add a random class that allows setting predictable seeds for testing

2022-04-21 02:26 UTC, bwrsandman commented on src/ECS/Components/Town.cpp
> +					assert(false); // TODO
Unfinished code and not clear

2022-04-21 02:26 UTC, bwrsandman commented on src/ECS/Components/Town.cpp
> +	uint32_t abodeCount = 0;            // TODO: Rename to fieldsAndPlannedTotal
Rename?

2022-04-21 02:26 UTC, bwrsandman commented on src/ECS/Map.cpp
> +	    coords.y * 10.0f / static_cast<float>(0x1000),
Should be `/ 0x10000`

2022-04-21 02:26 UTC, bwrsandman commented on src/ECS/Systems/LivingActionSystem.cpp
> +	    return -1;
`return false;`

2022-04-21 02:26 UTC, bwrsandman commented on src/ECS/Systems/LivingActionSystem.cpp
> +    },
Add missing initializers

2022-04-21 02:26 UTC, bwrsandman commented on src/ECS/Systems/LivingActionSystem.cpp
> +		auto& registry = Game::instance()->GetEntityRegistry();
Remove this line

2022-04-27 23:03 UTC, raffclar commented
About making this more "ECS". I think we should explore the way we update our systems per tick - but not in this PR. EnTT provides a minimal robust cooperative scheduler with lots of neat quirks like a graceful abort. Go to https://github.com/skypjack/entt/wiki/Crash-Course:-cooperative-scheduler and look at the "chains of processes" paragraph and you can see how we might be able to chain together our systems if a fairely logical way

2022-04-27 23:03 UTC, raffclar requested changes

2022-04-27 23:06 UTC, raffclar commented
The interactive debug gui is amazing by the way

2022-04-28 01:59 UTC, bwrsandman commented on src/Enums.h
> +static constexpr std::array<std::string_view, static_cast<size_t>(VillagerStates::_COUNT)> VillagerStateStrings = {
There should be 256 `VillagerStates` not including `_COUNT`. The first one is a 0.

2022-04-28 02:02 UTC, bwrsandman commented on src/Enums.h
> +static constexpr std::array<std::string_view, static_cast<size_t>(VillagerStates::_COUNT)> VillagerStateStrings = {
Good catch

2022-04-28 02:07 UTC, bwrsandman commented on src/ECS/Systems/LivingActionSystem.cpp
> +		SPDLOG_LOGGER_DEBUG(spdlog::get("ai"), "Villager #{}: Setting state {} -> {}",
If I set it to trace is that good enough?

2022-04-28 11:08 UTC, raffclar commented on src/ECS/Systems/LivingActionSystem.cpp
> +		SPDLOG_LOGGER_DEBUG(spdlog::get("ai"), "Villager #{}: Setting state {} -> {}",
Yeah trace is better

2022-04-28 20:38 UTC, raffclar commented
There's an infinite loop occurring in the fitBox function. Digging a bit deeper into now.

2022-04-29 00:07 UTC, raffclar approved these changes

2022-04-29 00:30 UTC, merged