Add minimal support for creature isle meshes and textures
openblack/openblack pull request #322
Opened 2022-01-08 22:08 UTC by raffclar

2022-01-09 19:35 UTC, bwrsandman requested changes
Could you add to the PackFIle.cpp doc at the top of the the source file

2022-01-10 01:41 UTC, raffclar commented
> PackFIle
For the PackFile, there's nothing to document but the L3DFile has some minor changes in CI, noticeably to do with DXT5 textures being present. Want me to document that?

2022-01-10 21:44 UTC, bwrsandman commented
Yeah a little information about the format would be a useful place to answer questions about the types of textures supported and such.

2022-01-11 02:45 UTC, raffclar commented
> Yeah a little information about the format would be a useful place to answer questions about the types of textures supported and such.

Nevermind the key change is in the PackFile

2022-01-11 02:51 UTC, raffclar commented on components/pack/src/PackFile.cpp
> -		if (header.ddsSize - sizeof(ddsHeader) - sizeof(uint32_t) != ddsHeader.pitchOrLinearSize)
@bwrsandman 
I'm still reading this example but I don't see any checks like that here: https://docs.microsoft.com/en-us/windows/uwp/gaming/complete-code-for-ddstextureloader
I've had to remove this check as the ddsSize field is larger than the pitchOrLinearSize for DXT5 textures.

2022-01-12 01:39 UTC, merged