Add names and types to info structs
openblack/openblack pull request #330
Opened 2022-01-11 04:42 UTC by bwrsandman

This is done thanks to the info*.txt files on the mac disk

2022-01-11 04:46 UTC, bwrsandman commented on src/InfoConstants.h
> +	uint32_t StartStrength;
lower case

2022-01-13 18:33 UTC, raffclar requested changes

2022-01-13 18:33 UTC, raffclar commented on src/InfoConstants.h
> +	float rainingAcceleratorMultiplier;
Spelling mistake

2022-01-15 15:30 UTC, bwrsandman commented on src/InfoConstants.h
> +	float rainingAcceleratorMultiplier;
what's the mistake?

2022-01-23 16:22 UTC, bwrsandman commented on src/AllMeshes.h
> +	_count
_COUNT

2022-01-23 16:22 UTC, bwrsandman commented on src/Enums.h
> +	_count
_COUNT

2022-01-23 16:22 UTC, bwrsandman commented on src/Enums.h
>  	None = 0,
Aren't there names for these countries?

2022-01-23 16:22 UTC, bwrsandman commented on src/Enums.h
> +	_Last = 2
_COUNT

2022-01-23 16:26 UTC, bwrsandman commented on src/Enums.h
> +	_COUNT
* Death reason already exists
* is count the same as last?

2022-01-24 21:55 UTC, bwrsandman commented on src/Enums.h
>  	None = 0,
Nope

2022-01-25 18:20 UTC, merged