Refine the alpha threshol, add blending
openblack/openblack pull request #331
Opened 2022-01-12 00:54 UTC by raffclar

2022-01-12 01:03 UTC, bwrsandman commented on assets/shaders/fs_object.sc
> +	// The alpha threshold different for each mesh
Mark as a todo

2022-01-12 01:04 UTC, bwrsandman commented
I'll have to run and compare to approve. Don't have the correct set up right now but will update.

2022-01-12 01:31 UTC, raffclar commented on assets/shaders/fs_object.sc
> +	// The alpha threshold different for each mesh
Done

2022-01-13 23:03 UTC, bwrsandman requested changes
Very good change for the trees, could you elaborate on possible sources of threshold per mesh?

I would like to avoid the case of going back and forth between different threshold values because this isn't the first time we change this bit of the shader.

2022-01-14 02:39 UTC, raffclar commented on assets/shaders/fs_object.sc
> +	const float alphaThreshold = 0.768627f;
The current value was retrieved though Nsight by looking at the draw calls for a tree on Land 1. Different meshes can have different thresholds. There's no observable pattern for the threshold yet.

2022-01-14 02:42 UTC, raffclar commented
The tree that's being drawn with this alpha threshold:
![image](https://user-images.githubusercontent.com/32263167/149442487-eee01f44-ba97-4d2c-b12b-d27f1f8adbaf.png)

2022-01-14 14:55 UTC, bwrsandman commented
With the discoveries of #334, I would say that these changes are insufficient.
Alpha threshold should only be used with specific render modes. The value of the threshold changes per primitive, so that value needs to be brought from the 5th byte of a primitive file to the draw call of the spans.

The shader should either be split or have logic that ignores alpha threshold when not used.

2022-01-14 19:00 UTC, bwrsandman commented on src/Renderer.cpp
> +				| BGFX_STATE_BLEND_EQUATION(BGFX_STATE_BLEND_EQUATION_ADD)
These are dependent on render mode. See the table I made: https://github.com/openblack/openblack/wiki/Vanilla-Render-Modes

2022-01-15 22:10 UTC, closed without merging