Use locator for exisiting raw files
openblack/openblack pull request #390
Opened 2022-04-22 12:44 UTC by bwrsandman

Resolves #388

2022-04-22 13:09 UTC, bwrsandman commented on src/Renderer.cpp
> +				static const auto textureId = entt::hashed_string("raw/smallbumpa");
This constant should be on the class

2022-04-22 13:09 UTC, bwrsandman commented on src/Renderer.cpp
> +			static const auto alphaId = entt::hashed_string("raw/Skya");
These constants should be on the class

2022-04-27 00:57 UTC, raffclar requested changes

2022-04-27 00:57 UTC, raffclar commented on src/3D/LandIsland.cpp
> -	_textureSmallBump->Create(256, 256, 1, Format::R8, Wrapping::Repeat, smallbumpa, static_cast<uint32_t>(file->Size()));
Getting odd visual artifacts on my end. Different format perhaps?

![image](https://user-images.githubusercontent.com/32263167/165415773-27e7120f-3762-4a11-92a5-143371ab34e9.png)

2022-04-27 00:57 UTC, raffclar commented on src/3D/LandIsland.cpp
> -	_textureSmallBump->Create(256, 256, 1, Format::R8, Wrapping::Repeat, smallbumpa, static_cast<uint32_t>(file->Size()));
Logic within the loader for comparison:

```texture->Create(width, height, 1, format, graphics::Wrapping::ClampEdge, data.data(), static_cast<uint32_t>(data.size()));```

2022-04-27 00:57 UTC, raffclar commented on src/3D/Water.cpp
> -	_texture->Create(textureWidth, textureHeight, 1, Format::RGB8, Wrapping::Repeat, waterTextureData.data(),
Same issue here. The water plane has no texture and the above differs from the texture loader

![image](https://user-images.githubusercontent.com/32263167/165417021-a4082661-377a-41b3-8b07-0b11be85c41b.png)

2022-04-27 02:20 UTC, raffclar approved these changes
Nice one 👍

2022-04-27 03:44 UTC, merged