RNGManager access through Locator
openblack/openblack pull request #407
Opened 2022-04-27 22:24 UTC by FalseIlyu

Simplest way to make the RNGManager access through Locator

2022-04-27 23:36 UTC, raffclar requested changes

2022-04-27 23:36 UTC, raffclar commented on src/Locator.h
> +	using rng = entt::service_locator<RNGManager>;
Create an interface for RNGManager called `RNGManagerInterface`. We don't want to couple the locator to an implementation.

2022-04-27 23:36 UTC, raffclar commented on src/Game.cpp
> +	Locator::rng::set<RNGManager>();
👍

2022-04-29 00:06 UTC, bwrsandman commented on src/Common/RNG.h
> +	virtual ~RNGInterface() {}
Move the implementation to the implementation file.
```
~RNGInterface::RNGInterface() = default;
```

2022-04-30 10:47 UTC, bwrsandman commented on src/Common/RNGManager.cpp
> +	thread_local std::mt19937 tgenerator(time(nullptr));
Fix these warning:
>  'argument': conversion from 'time_t' to 'unsigned int', possible loss of data

2022-04-30 10:51 UTC, bwrsandman requested changes
I feel like the design here is wrong.

If we're going through the Locator pattern, debug and non-debug should be two different implementations.
of `RNGInterface`.

2022-05-01 22:49 UTC, bwrsandman requested changes
Same as previously. With the locator pattern, it's best to have two implementations of RNG.h, which the name should be improved like: RandomNumberManager.h
It should provide two interfaces to the locator:
* RandomNumberManagerProduction.h
* RandomNumberManagerTesting.h

2022-05-01 22:51 UTC, bwrsandman commented on src/Game.cpp
> +	Locator::rng::set<RNGManager>();
This is where you would either set the debug or production rng implementation

2022-05-02 12:12 UTC, bwrsandman requested changes

2022-05-02 12:12 UTC, bwrsandman commented on src/Common/RandomNumberManagerProduction.cpp
> +	return rMutex;
Is a mutex necessary in production?

2022-05-02 12:12 UTC, bwrsandman commented on src/Common/RandomNumberManagerProduction.cpp
> +}
Do we need to manually set seed in production?

2022-05-02 12:59 UTC, FalseIlyu commented on src/Common/RandomNumberManagerProduction.cpp
> +	return rMutex;
We need to have the lock callable for NextValue even if it is not used, it shouldn't be necessary for production but i don't quite know what could be done to have NextValue() be separate for test and production as most of the idea i found need for NextValue to not use template.

2022-05-02 14:00 UTC, bwrsandman commented on src/Common/RandomNumberManagerProduction.cpp
> +}
In that case wouldn't that be another implementation?
Maybe add a MultiplayerSynced implementation

2022-05-20 22:28 UTC, bwrsandman approved these changes
My issue remains that it would be ideal if we could have the RNG manager interface not require optional or mutex.

2022-05-20 22:28 UTC, bwrsandman commented on src/Common/RandomNumberManager.h
> +#include <functional>
Are you sure you need this include?

2022-05-22 16:51 UTC, bwrsandman requested changes
Please fix the warnings in `Files changed`

2022-05-22 19:41 UTC, raffclar approved these changes

2022-05-22 22:55 UTC, bwrsandman approved these changes

2022-05-22 22:57 UTC, merged