temple-glow-format - Add support/tools for mapping temple light sources
openblack/openblack pull request #677
Opened 2023-12-31 19:03 UTC by raffclar

This PR adds support for the "glw" file format. This format directs the position & properties of the light sources (glows) within the temple interior.

Most of the known fields are from fuzzing the format and inspecting vanilla ingame changes so churn with the structs are to be expected until we know for certain which bytes account for what.

2024-07-11 19:06 UTC, bwrsandman commented on src/ECS/Archetypes/GlowArchetype.cpp
> +std::array<entt::entity, 2> GlowArchetype::Create(const LightEmitter& emitter, components::TempleRoom room)
This should not be a suggested fix since those are included in the header....

2024-08-07 22:04 UTC, bwrsandman requested changes

2024-08-07 22:04 UTC, bwrsandman commented on src/Renderer.cpp
> +		if (!desc.drawTestModel)
This looks like it was negated accidentally

2024-08-07 22:04 UTC, bwrsandman commented on src/Resources/Loaders.h
> +#include <entt/entt.hpp>
Expensive header and not needed
```suggestion
```

2024-08-07 22:55 UTC, raffclar commented
I'll do a final rebase before merge

2024-08-08 03:27 UTC, bwrsandman commented
Still the issue with `desc.drawTestModel`

2024-08-08 20:57 UTC, raffclar commented
> Still the issue with `desc.drawTestModel`

Sorted and rebased. I think we're good to go once CI passes

2024-08-08 21:03 UTC, bwrsandman commented
Is there a depth test missing?

![image](https://github.com/user-attachments/assets/148318d6-d368-42ef-af77-6f1862c390fd)

2024-08-08 21:22 UTC, bwrsandman requested changes
- [ ] Fix the inverse depth
- [ ] Simplify `BGFX_STATE_BLEND_FUNC`
- [ ] Remove `drawGlowEffects` config and profiler category

2024-08-08 21:22 UTC, bwrsandman commented on src/Renderer.cpp
> +					                   BGFX_STATE_BLEND_EQUATION(BGFX_STATE_BLEND_EQUATION_ADD));
```suggestion
					    bgfx::setState(0 | BGFX_STATE_DEPTH_TEST_GREATER | BGFX_STATE_WRITE_RGB | BGFX_STATE_WRITE_A |
					                   BGFX_STATE_BLEND_FUNC(BGFX_STATE_BLEND_SRC_ALPHA, BGFX_STATE_BLEND_ONE) |
					                   BGFX_STATE_BLEND_EQUATION(BGFX_STATE_BLEND_EQUATION_ADD));
```

2024-08-08 21:22 UTC, bwrsandman commented on src/Renderer.cpp
> +
If this isn't used, then it should be deleted
```suggestion
```

2024-08-08 21:22 UTC, bwrsandman commented on src/Renderer.h
> +		bool drawGlowEffects;
```suggestion
```

2024-08-08 21:22 UTC, bwrsandman commented on src/Game.cpp
> +			    /*drawGlowEffects =*/_config.drawGlowEffects,
```suggestion
```

2024-08-08 21:22 UTC, bwrsandman commented on src/Game.h
> +		bool drawGlowEffects {true};
```suggestion
```

2024-08-08 21:22 UTC, bwrsandman commented on src/Profiler.h
> +		ReflectionDrawGlowEffects,
```suggestion
```

2024-08-08 21:22 UTC, bwrsandman commented on src/Profiler.h
> +		MainPassDrawGlowEffects,
```suggestion
```

2024-08-08 23:05 UTC, bwrsandman approved these changes

2024-08-08 23:40 UTC, merged