Unifying the filesystem interface (eg. no more check)
openblack/openblack pull request #706
Opened 2024-04-05 19:22 UTC by FalseIlyu

The purpose of this PR is to remove the need of checking what type of filesystem to use before reading a file either at compile type (as we have currently to handle android) or at runtime (as proposed in #673).

It divides responsibility as follows \:
- Parsers get data from a stream and build game asset from it.
- The filesystem look for the data and organise it as a istream.
- The stream handles direct access to the data.

As a first draft i moved `void ReadFile(std::istream& stream)` in all parsers from a private to a public method.
Added a `std::unique_ptr<std::istream> GetData(const std::filesystem::path& path)` as the method to ask access to data from the filesystem.
Replaced place where we had to choose between `Open(Locator::filesystem::value().ReadAll(path));` and `Open(path)` with `ReadFile(*Locator::filesystem::value().GetData(path));`
Copied the membuf from the component into android and made it own a copy of the file data (mostly a lazy way to ensure the data was there while being read by the buffer) i also allowed it to be initialized by a vector of byte.

I propose this as draft as i wish to have comment about change that would be necessary or better to implement this (and if such a change is agreeable). Once/while implementation detail are discussed apps and parsers still need to be changed before this gets ready for merge (removing the possibility to read file from parsers and the implied changes it will need on apps).

This would replace #673 if merged before. I didn't look if it would be a pain to modify #674 to make it work with the changes brought here if it is merging #674 should take priority and this PR should be responsible to make it work (tbc i presume it means i will do it).

2024-04-05 20:17 UTC, bwrsandman commented
I'm not sure why the Files in components are virtual. They should not be.
Another thing I'm worried about is language binding. The original intent of splitting off file loading code was they they would be easier to call from C code and to make language bindings. We shouldn't lose sight of this.

2024-04-06 09:36 UTC, FalseIlyu commented
> Another thing I'm worried about is language binding. The original intent of splitting off file loading code was they they would be easier to call from C code and to make language bindings. We shouldn't lose sight of this.

This mostly concerns components, no ? Because in this case nothing really force us to remove the `void Open` method and use this in engine to make thing more straightforward for use (with the idea that with the actual file reading decoupled from the filesystem it is going to make it easier to test thing when we actually go forth we looking to performance issue). Even in the case of the filesystem we can keep the `readAll` method accessible as something easier to work with from C (as for the moment we use it to build the stream in Android and i don't see it being not usefull to us in any case, it would just mean keeping it public).

2024-04-23 22:41 UTC, bwrsandman commented
If you rebase, the tests will pass

2024-05-27 20:56 UTC, bwrsandman commented on components/anm/include/ANMFile.h
> +#include <istream>
I think you can get away with forward declaring this

2024-08-08 19:27 UTC, bwrsandman requested changes
Few nits to fix and then it can be merged

2024-08-08 19:27 UTC, bwrsandman commented on components/lnd/include/LNDFile.h
> +#include <istream>
Not necessary to have this expensive header
```suggestion
```

2024-08-08 19:27 UTC, bwrsandman commented on components/l3d/include/L3DFile.h
> +#include <istream>
Ditto
```suggestion
```

2024-08-08 19:27 UTC, bwrsandman commented on src/FileSystem/DefaultFileSystem.h
> +#include <istream>
```suggestion
```
Same. Since we use `std::unique_ptr<std::istream>` in the header, it can be forward declared.

2024-08-08 19:27 UTC, bwrsandman commented on src/FileSystem/FileSystemInterface.h
> +#include <istream>
```suggestion
```
Same

2024-08-08 19:48 UTC, bwrsandman approved these changes

2024-08-08 20:25 UTC, merged