C++23 transition
openblack/openblack pull request #741
Opened 2024-05-17 18:10 UTC by FalseIlyu

Changes towards the accomplishment of #656, implements #522

Depends on 
- #719

This apply only in /src
* [ ]  Search all TODO's related to c++ version and implement with newer c++ features such as https://github.com/openblack/openblack/issues/522
* [ ]  Revisit issues related to version compatibility (?)
* [x]  Revisit complicated templates and simplify using `concepts` (such as script to functions)
* [x]  Fix errors in build
* [x]  Any github action compiler download or settings (will need assistance)

2024-05-22 18:05 UTC, bwrsandman requested changes
Looks really good. Just a couple fixes

2024-05-22 18:24 UTC, FalseIlyu commented on src/Camera/DefaultWorldCameraModel.cpp
> +		for (auto [score, flyingScore] : std::views::zip(scores, k_FlyingScoreAngles))
It seems not as using `auto&` will make the decomposition a `std::tuple<double &,const _double &> &` (and throw a compilation) so it's seems to infer that they are references.
I'll need to do some research to know if this is not a windows thing though.

2024-05-22 19:04 UTC, FalseIlyu commented on src/Camera/DefaultWorldCameraModel.cpp
> +const auto k_GetMouseHit = [](auto hit) -> std::optional<glm::vec3> { return hit.position; };
Moving it to transform as it is an utility for Transform type

2024-05-22 23:57 UTC, bwrsandman commented on src/ECS/Components/Transform.h
> +const auto k_GetTransformPosition = [](Transform hit) constexpr -> std::optional<glm::vec3> { return hit.position; };
At this point it doesn't have to be a lambda and can be an inline function. Also make sure hit is a reference to avoid needlessly copying it.

2024-05-23 12:31 UTC, bwrsandman approved these changes
Good work!

2024-05-23 12:31 UTC, merged