Convert Config, Camera and Info to locator services
openblack/openblack pull request #781
Opened 2024-08-16 13:34 UTC by bwrsandman

Supercedes
* #778 
* #779 
* #780

2024-08-17 18:52 UTC, Daniels118 commented on src/Debug/Gui.cpp
> +		const std::string strId = name + " Arrow";
```suggestion
		const auto strId = name + " Arrow";
```

2024-08-17 18:59 UTC, Daniels118 commented on src/Debug/Console.cpp
> +	const ImGuiIO& io = ImGui::GetIO();
```suggestion
	const auto& io = ImGui::GetIO();
```

2024-08-17 19:01 UTC, Daniels118 commented on src/Debug/Console.cpp
> +	const bool copyToClipboard = ImGui::SmallButton("Copy");
```suggestion
	const auto copyToClipboard = ImGui::SmallButton("Copy");
```

2024-08-17 19:02 UTC, Daniels118 commented on src/Debug/Console.cpp
> +	const float footerHeightToReserve = ImGui::GetStyle().ItemSpacing.y + ImGui::GetFrameHeightWithSpacing();
```suggestion
	const auto footerHeightToReserve = ImGui::GetStyle().ItemSpacing.y + ImGui::GetFrameHeightWithSpacing();
```

2024-08-17 19:04 UTC, Daniels118 commented on src/Debug/Gui.cpp
> +	const ImGuiIO& io = ImGui::GetIO();
```suggestion
	const auto& io = ImGui::GetIO();
```

2024-08-17 19:05 UTC, Daniels118 commented on src/Debug/Gui.cpp
>  	ImGuiIO& io = ImGui::GetIO();
Can be declared as `const auto`?

2024-08-17 19:06 UTC, Daniels118 commented on src/Debug/Gui.cpp
> +	const bgfx::RendererType::Enum type = bgfx::getRendererType();
Can use `auto` type?

2024-08-17 19:08 UTC, Daniels118 commented on src/Debug/Gui.cpp
>  				float fieldOfView = glm::degrees(camera.GetHorizontalFieldOfView());
Can be declared as `const auto`?

2024-08-18 10:35 UTC, Daniels118 reviewed
Using `auto` where applicable.

2024-08-18 18:05 UTC, Daniels118 requested changes
What's the purpose of 23d7dfe235bb7b113fb64d3e5cd2648ab63ab897? It improves the code readability a bit, but it could increase the load time on low-end devices. If you want to keep the improved readability, maybe it would be better to change the type of `_infoConstants` to `unique_ptr`.

2024-08-18 19:31 UTC, bwrsandman commented
It's prep for the following commit which makes it into a `shared_ptr` through the locator service. The 0.5MB copy issue is also removed in the next commit.

2024-08-18 20:03 UTC, Daniels118 approved these changes

2024-08-18 20:41 UTC, raffclar approved these changes

2024-08-18 20:42 UTC, merged

2024-08-18 20:43 UTC, raffclar commented
Really nice work. One step closer to `Game::Instance()` being removed